    // Unexpire passwords for development mode
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")
    write "Passwords unexpired for all users",!

    set tURL = "https://pm.community.intersystems.com/packages/zpm/latest/installer"
    set r = ##class(%Net.HttpRequest).%New()
    set r.Server = "pm.community.intersystems.com"
    set r.SSLConfiguration = "ISC.FeatureTracker.SSL.Config"
    do r.Get("/packages/zpm/latest/installer")
    do $system.OBJ.LoadStream(r.HttpResponse.Data,"c")

    // Enable callin for Embedded Python - see merge.cpf
    do ##class(Security.Services).Get("%Service_CallIn",.prop)
    set prop("Enabled")=1
    set prop("AutheEnabled")=48
    do ##class(Security.Services).Modify("%Service_CallIn",.prop)

    zpm "enable -community"

    set sc=$SYSTEM.OBJ.Load("/home/irisowner/dev/App.Installer.cls","ck")
    if $SYSTEM.Status.IsError(sc) write $SYSTEM.Status.GetErrorText(sc),!
    set sc=##class(App.Installer).setup()
    if $SYSTEM.Status.IsError(sc) write $SYSTEM.Status.GetErrorText(sc),!

    // Create /_vscode web app to support intersystems-community.testingmanager VS Code extension
    zpm "install vscode-per-namespace-settings"

    // Configure %UnitTest in AI_HUB_STUDIO to suit the VS Code extension
    set ^UnitTestRoot="/usr/irissys/.vscode/AI_HUB_STUDIO/UnitTestRoot"

    halt
